#!/bin/bash

alias poweroff='systemctl poweroff'
alias reboot='systemctl reboot'
alias suspend='systemctl suspend'
alias hibernate='systemctl hibernate'

alias l='ls'
alias ls='ls -F --color --group-directories-first'
alias ll='ls -oh'
alias la='ls -A'
alias lla='ll -A'

if [ -x $CARGO_HOME/bin/eza ]; then
	alias ls='eza -F --group-directories-first'
	alias ll='ls -l'
	alias lt='ls -T'
fi
[ -x $CARGO_HOME/bin/xcp ] && alias cp='xcp'
[ -x $CARGO_HOME/bin/rg ] && alias grep='rg'
[ -x $CARGO_HOME/bin/fd ] && alias find='fd'
[ -x $CARGO_HOME/bin/fd ] && alias find='fd'
