#!/bin/sh

export EDITOR='emacs'

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache

export HISTFILE=$XDG_CACHE_HOME/bash_history
export HISTSIZE=9999
export HISTCONTROL='erasedups:ignorespace'

[ -d $HOME/.local/bin ] && export PATH=$PATH:$HOME/.local/bin

export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export CARGO_HOME=$XDG_DATA_HOME/cargo
[ -d $CARGO_HOME ] && export PATH=$CARGO_HOME/bin:$PATH

if [ -z $WAYLAND_DISPLAY ] && [ $XDG_VTNR -eq 1 ]; then
	[ -x /usr/bin/sway ] && exec sway
fi
